apiVersion: v1
kind: Service
metadata:
  name: challengen5api-service
spec:
  selector:
    app: challengen5api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080    # Specify a static port for NodePort
  type: NodePort        # Change the service type to NodePort